export interface FieldGapData {
  fieldName: string;
  category: 'Requisition Report' | 'Candidate Report' | 'Workflow Dates';
  status: 'ok' | 'no' | 'blank';
  backendRef: string;
  newmontFieldName: string;
  manipulationNeeded: string;
  kfNotes: string;
  newmontComments: string;
  kfImpactToReporting: string;
}

const f = (
  fieldName: string,
  category: FieldGapData['category'],
  status: FieldGapData['status'],
  backendRef: string
): FieldGapData => ({
  fieldName,
  category,
  status,
  backendRef,
  newmontFieldName: '',
  manipulationNeeded: '',
  kfNotes: '',
  newmontComments: '',
  kfImpactToReporting: '',
});

export const fieldGapData: FieldGapData[] = [
  // --- Requisition Report (77 fields: 52 ok, 20 no, 5 blank) ---
  f('Job Req ID', 'Requisition Report', 'ok', 'req.id'),
  f('Requisition Status', 'Requisition Report', 'ok', 'req.status'),
  f('Job Title', 'Requisition Report', 'ok', 'req.title'),
  f('Business Unit', 'Requisition Report', 'ok', 'req.bu'),
  f('Pay Grade', 'Requisition Report', 'ok', 'req.pay_grade'),
  f('Date Created', 'Requisition Report', 'ok', 'req.created_date'),
  f('Approved Date', 'Requisition Report', 'ok', 'req.approved_date'),
  f('Closed Date', 'Requisition Report', 'ok', 'req.closed_date'),
  f('Job Code', 'Requisition Report', 'ok', 'req.job_code'),
  f('Job Family', 'Requisition Report', 'ok', 'req.job_family'),
  f('Job Level', 'Requisition Report', 'ok', 'req.job_level'),
  f('Department ID', 'Requisition Report', 'ok', 'req.dept_id'),
  f('Department Name', 'Requisition Report', 'ok', 'req.dept_name'),
  f('Cost Center', 'Requisition Report', 'ok', 'req.cost_center'),
  f('Location Code', 'Requisition Report', 'ok', 'req.loc_code'),
  f('Country', 'Requisition Report', 'ok', 'req.country'),
  f('State/Province', 'Requisition Report', 'ok', 'req.state'),
  f('City', 'Requisition Report', 'ok', 'req.city'),
  f('Postal Code', 'Requisition Report', 'ok', 'req.postal_code'),
  f('Hiring Manager ID', 'Requisition Report', 'ok', 'req.hm_id'),
  f('Hiring Manager Name', 'Requisition Report', 'ok', 'req.hm_name'),
  f('Recruiter ID', 'Requisition Report', 'ok', 'req.recruiter_id'),
  f('Recruiter Name', 'Requisition Report', 'ok', 'req.recruiter_name'),
  f('Primary Recruiter', 'Requisition Report', 'ok', 'req.primary_recruiter'),
  f('Coordinator Name', 'Requisition Report', 'ok', 'req.coord_name'),
  f('Sourcer Name', 'Requisition Report', 'ok', 'req.sourcer_name'),
  f('Employment Type', 'Requisition Report', 'ok', 'req.emp_type'),
  f('Time Type', 'Requisition Report', 'ok', 'req.time_type'),
  f('Full/Part Time', 'Requisition Report', 'ok', 'req.full_part_time'),
  f('Standard Hours', 'Requisition Report', 'ok', 'req.std_hours'),
  f('FLSA Status', 'Requisition Report', 'ok', 'req.flsa'),
  f('Target Headcount', 'Requisition Report', 'ok', 'req.headcount'),
  f('Open Openings', 'Requisition Report', 'ok', 'req.openings'),
  f('Filled Openings', 'Requisition Report', 'ok', 'req.filled_openings'),
  f('Job Profile', 'Requisition Report', 'ok', 'req.job_profile'),
  f('Union Code', 'Requisition Report', 'ok', 'req.union_code'),
  f('Legal Entity', 'Requisition Report', 'ok', 'req.legal_entity'),
  f('Division', 'Requisition Report', 'ok', 'req.division'),
  f('Region', 'Requisition Report', 'ok', 'req.region'),
  f('Work Shift', 'Requisition Report', 'ok', 'req.shift'),
  f('Currency', 'Requisition Report', 'ok', 'req.currency'),
  f('Minimum Salary', 'Requisition Report', 'ok', 'req.min_sal'),
  f('Maximum Salary', 'Requisition Report', 'ok', 'req.max_sal'),
  f('Midpoint Salary', 'Requisition Report', 'ok', 'req.mid_sal'),
  f('Target Salary', 'Requisition Report', 'ok', 'req.target_sal'),
  f('Relocation Offered', 'Requisition Report', 'ok', 'req.reloc'),
  f('Travel Percentage', 'Requisition Report', 'ok', 'req.travel'),
  f('Education Required', 'Requisition Report', 'ok', 'req.education'),
  f('Experience Required', 'Requisition Report', 'ok', 'req.exp_req'),
  f('Primary Skill', 'Requisition Report', 'ok', 'req.primary_skill'),
  f('Posting Type', 'Requisition Report', 'ok', 'req.post_type'),
  f('Approval Flow ID', 'Requisition Report', 'ok', 'req.approval_id'),
  f('Time to Fill', 'Requisition Report', 'no', 'req.time_to_fill'),
  f('Age of Requisition', 'Requisition Report', 'no', 'req.age'),
  f('Sourcing Channel Cost', 'Requisition Report', 'no', 'req.channel_cost'),
  f('Agency Fee Percentage', 'Requisition Report', 'no', 'req.agency_fee_pct'),
  f('Estimated Cost of Hire', 'Requisition Report', 'no', 'req.est_cost_hire'),
  f('Actual Cost of Hire', 'Requisition Report', 'no', 'req.act_cost_hire'),
  f('Budget Approved', 'Requisition Report', 'no', 'req.budget_approved'),
  f('Position Control Number', 'Requisition Report', 'no', 'req.pos_control_num'),
  f('Visa Sponsorship Allowed', 'Requisition Report', 'no', 'req.visa_spons'),
  f('Security Clearance Required', 'Requisition Report', 'no', 'req.clearance'),
  f('Assessment Type Required', 'Requisition Report', 'no', 'req.assessment_type'),
  f('Interviewer Panel List', 'Requisition Report', 'no', 'req.interviewer_list'),
  f('Internal Job Description', 'Requisition Report', 'no', 'req.desc_internal'),
  f('External Job Description', 'Requisition Report', 'no', 'req.desc_external'),
  f('Posting Duration Days', 'Requisition Report', 'no', 'req.post_duration'),
  f('Pre-screen Questionnaire ID', 'Requisition Report', 'no', 'req.prescreen_id'),
  f('Requisition Group', 'Requisition Report', 'no', 'req.req_group'),
  f('Salary Grade Minimum', 'Requisition Report', 'no', 'req.grade_min'),
  f('Salary Grade Maximum', 'Requisition Report', 'no', 'req.grade_max'),
  f('On-Hold Date', 'Requisition Report', 'no', 'req.on_hold_date'),
  f('Requisition Hold Reason', 'Requisition Report', 'blank', 'req.hold_reason'),
  f('Cancellation Reason', 'Requisition Report', 'blank', 'req.cancel_reason'),
  f('Requisition Template ID', 'Requisition Report', 'blank', 'req.template_id'),
  f('Target Fill Date', 'Requisition Report', 'blank', 'req.target_fill_date'),
  f('Justification Code', 'Requisition Report', 'blank', 'req.justification'),

  // --- Candidate Report (32 fields: 22 ok, 10 no, 0 blank) ---
  f('Candidate ID', 'Candidate Report', 'ok', 'cand.id'),
  f('First Name', 'Candidate Report', 'ok', 'cand.first_name'),
  f('Last Name', 'Candidate Report', 'ok', 'cand.last_name'),
  f('Email', 'Candidate Report', 'ok', 'cand.email'),
  f('Phone', 'Candidate Report', 'ok', 'cand.phone'),
  f('Application Source', 'Candidate Report', 'ok', 'cand.source'),
  f('Current Stage', 'Candidate Report', 'ok', 'cand.stage'),
  f('Current Job Title', 'Candidate Report', 'ok', 'cand.current_title'),
  f('Current Employer', 'Candidate Report', 'ok', 'cand.current_emp'),
  f('Years of Experience', 'Candidate Report', 'ok', 'cand.years_exp'),
  f('Location (City)', 'Candidate Report', 'ok', 'cand.city'),
  f('Location (Country)', 'Candidate Report', 'ok', 'cand.country'),
  f('Willing to Relocate', 'Candidate Report', 'ok', 'cand.reloc'),
  f('Notice Period', 'Candidate Report', 'ok', 'cand.notice_period'),
  f('Salary Expectation', 'Candidate Report', 'ok', 'cand.salary_exp'),
  f('Referral Name', 'Candidate Report', 'ok', 'cand.referral'),
  f('EEO Gender', 'Candidate Report', 'ok', 'cand.gender'),
  f('EEO Ethnicity', 'Candidate Report', 'ok', 'cand.ethnicity'),
  f('Veteran Status', 'Candidate Report', 'ok', 'cand.veteran'),
  f('Disability Status', 'Candidate Report', 'ok', 'cand.disability'),
  f('Candidate Type (Internal/External)', 'Candidate Report', 'ok', 'cand.type'),
  f('Rejection Reason', 'Candidate Report', 'ok', 'cand.rej_reason'),
  f('Resume Attachment', 'Candidate Report', 'no', 'cand.resume'),
  f('Application Date', 'Candidate Report', 'no', 'cand.app_date'),
  f('Screening Outcome', 'Candidate Report', 'no', 'cand.screening_outcome'),
  f('Candidate Status', 'Candidate Report', 'no', 'cand.status'),
  f('Interviewer Rating', 'Candidate Report', 'no', 'cand.interviewer_rating'),
  f('Background Check Status', 'Candidate Report', 'no', 'cand.bgc_status'),
  f('Offer Details', 'Candidate Report', 'no', 'cand.offer_details'),
  f('Drug Screen Status', 'Candidate Report', 'no', 'cand.drug_status'),
  f('Medical Clearance Status', 'Candidate Report', 'no', 'cand.medical_status'),
  f('Visa Check Status', 'Candidate Report', 'no', 'cand.visa_status'),

  // --- Workflow Dates (18 fields: 10 ok, 8 no, 0 blank) ---
  f('Requisition Approved Date', 'Workflow Dates', 'ok', 'wf.req_approved_date'),
  f('Post Date', 'Workflow Dates', 'ok', 'wf.post_date'),
  f('Sourcing Start Date', 'Workflow Dates', 'ok', 'wf.source_start_date'),
  f('First Resume Sent Date', 'Workflow Dates', 'ok', 'wf.first_resume_date'),
  f('First Interview Date', 'Workflow Dates', 'ok', 'wf.first_int_date'),
  f('Second Interview Date', 'Workflow Dates', 'ok', 'wf.second_int_date'),
  f('Final Interview Date', 'Workflow Dates', 'ok', 'wf.final_int_date'),
  f('Bgr Check Completed Date', 'Workflow Dates', 'ok', 'wf.bgc_completed_date'),
  f('Onboarding Start Date', 'Workflow Dates', 'ok', 'wf.onboarding_start_date'),
  f('Target Start Date', 'Workflow Dates', 'ok', 'wf.target_start_date'),
  f('Intake Meeting Date', 'Workflow Dates', 'no', 'wf.intake_date'),
  f('KF Assigned Date', 'Workflow Dates', 'no', 'wf.kf_assigned_date'),
  f('Req Shortlist Date', 'Workflow Dates', 'no', 'wf.shortlist_date'),
  f('Verbal Offer Date', 'Workflow Dates', 'no', 'wf.verbal_offer_date'),
  f('Written Offer Date', 'Workflow Dates', 'no', 'wf.written_offer_date'),
  f('Offer Accepted Date', 'Workflow Dates', 'no', 'wf.offer_accepted_date'),
  f('Bgr Check Initiated Date', 'Workflow Dates', 'no', 'wf.bgc_initiated_date'),
  f('Actual Start Date', 'Workflow Dates', 'no', 'wf.actual_start_date'),
];
