export const MOCK_DATA = {
  TOTAL: 19292,
  SLA_TARGET: 75,
  kpis: [
    { id: 'reqs', label: 'Total Requisitions', value: 19292, suffix: '', color: 'var(--accent)', icon: 'layers',
      trend: { dir: 'up', val: '+8.4%', cls: 'trend-up' }, note: 'vs. prior 12 mo' },
    { id: 'fill', label: 'Fill Rate', value: 73.6, suffix: '%', decimals: 1, color: 'var(--green)', icon: 'target',
      trend: { dir: 'up', val: '+2.1 pts', cls: 'trend-up' }, note: 'rolling 90-day' },
    { id: 'ttf', label: 'Avg Time to Fill', value: 80.1, suffix: ' days', decimals: 1, color: 'var(--amber)', icon: 'clock',
      trend: { dir: 'down', val: '−6.3 days', cls: 'trend-good-down' }, note: 'improving' },
    { id: 'cancel', label: 'Cancel Rate', value: 21.1, suffix: '%', decimals: 1, color: 'var(--red)', icon: 'alert',
      trend: { dir: 'flat', val: '+0.4 pts', cls: 'trend-warn' }, note: 'watch — above target' },
    { id: 'open', label: 'Open Reqs', value: 733, suffix: '', color: 'var(--purple)', icon: 'folder',
      trend: { dir: 'flat', val: '733 active', cls: 'trend-flat' }, note: '3.8% of pipeline' },
    { id: 'hold', label: 'On Hold', value: 212, suffix: '', color: 'var(--gray)', icon: 'pause',
      trend: { dir: 'flat', val: '1.1% of total', cls: 'trend-flat' }, note: 'see Hold Analysis' },
  ],
  ttfByCountry: [
    { country: 'Costa Rica', flag: '🇨🇷', days: 46, open: 84 },
    { country: 'Ghana', flag: '🇬🇭', days: 59, open: 71 },
    { country: 'Papua New Guinea', flag: '🇵🇬', days: 105, open: 96 },
    { country: 'Suriname', flag: '🇸🇷', days: 148, open: 58 },
    { country: 'Chile', flag: '🇨🇱', days: 190, open: 113 },
  ],
  statusDist: [
    { name: 'Filled', pct: 73.6, count: 14199, color: 'var(--green)' },
    { name: 'Cancelled', pct: 21.1, count: 4071, color: 'var(--red)' },
    { name: 'Open', pct: 3.8, count: 733, color: 'var(--accent)' },
    { name: 'On Hold', pct: 1.1, count: 212, color: 'var(--amber)' },
  ],
  countries: [
    { country: 'Costa Rica', flag: '🇨🇷', ttf: 46, open: 84, coverage: 96, gap: 3 },
    { country: 'Ghana', flag: '🇬🇭', ttf: 59, open: 71, coverage: 88, gap: 6 },
    { country: 'United States', flag: '🇺🇸', ttf: 62, open: 92, coverage: 91, gap: 5 },
    { country: 'Canada', flag: '🇨🇦', ttf: 68, open: 47, coverage: 89, gap: 4 },
    { country: 'Mexico', flag: '🇲🇽', ttf: 39, open: 39, coverage: 84, gap: 7 },
    { country: 'Dominican Rep.', flag: '🇩🇴', ttf: 74, open: 21, coverage: 82, gap: 3 },
    { country: 'Australia', flag: '🇦🇺', ttf: 88, open: 64, coverage: 79, gap: 9 },
    { country: 'Peru', flag: '🇵🇪', ttf: 96, open: 55, coverage: 74, gap: 11 },
    { country: 'Papua New Guinea', flag: '🇵🇬', ttf: 105, open: 96, coverage: 68, gap: 18 },
    { country: 'Argentina', flag: '🇦🇷', ttf: 119, open: 43, coverage: 71, gap: 8 },
    { country: 'Ecuador', flag: '🇪🇨', ttf: 134, open: 29, coverage: 64, gap: 10 },
    { country: 'Suriname', flag: '🇸🇷', ttf: 148, open: 58, coverage: 61, gap: 14 },
    { country: 'Chile', flag: '🇨🇱', ttf: 190, open: 113, coverage: 54, gap: 27 },
  ],
  families: ['Mining Ops', 'Process Plant', 'Maintenance', 'Geology & Exploration', 'HSE', 'Supply Chain', 'Finance & Admin'],
  heatRegions: ['Costa Rica', 'Ghana', 'Australia', 'Peru', 'Suriname', 'Chile'],
  heat: [
    { family: 'Mining Ops', cells: [92, 88, 77, 72, 59, 52] },
    { family: 'Process Plant', cells: [90, 85, 75, 70, 58, 50] },
    { family: 'Maintenance', cells: [94, 87, 79, 73, 61, 54] },
    { family: 'Geology & Exploration', cells: [88, 80, 71, 65, 50, 42] },
    { family: 'HSE', cells: [96, 91, 84, 78, 64, 58] },
    { family: 'Supply Chain', cells: [91, 84, 76, 71, 59, 51] },
    { family: 'Finance & Admin', cells: [98, 94, 89, 83, 72, 65] }
  ],
  slaCountries: [
    { name: 'Costa Rica', flag: '🇨🇷', base: 46 },
    { name: 'Ghana', flag: '🇬🇭', base: 59 },
    { name: 'United States', flag: '🇺🇸', base: 62 },
    { name: 'Canada', flag: '🇨🇦', base: 68 },
    { name: 'Mexico', flag: '🇲🇽', base: 71 },
    { name: 'Dominican Rep.', flag: '🇩🇴', base: 74 },
    { name: 'Australia', flag: '🇦🇺', base: 88 },
    { name: 'Peru', flag: '🇵🇪', base: 96 },
    { name: 'Papua New Guinea', flag: '🇵🇬', base: 105 },
    { name: 'Argentina', flag: '🇦🇷', base: 119 },
    { name: 'Ecuador', flag: '🇪🇨', base: 134 },
    { name: 'Suriname', flag: '🇸🇷', base: 148 },
    { name: 'Chile', flag: '🇨🇱', base: 190 },
  ],
  reqRows: [
    { id: 'REQ-84210', title: 'Senior Mining Engineer', country: 'Chile', flag: '🇨🇱', status: 'Open', statusCls: 'b-open', days: 113, recruiter: 'M. Reyes', prio: 'Critical', prioCls: 'b-crit' },
    { id: 'REQ-84247', title: 'Process Plant Operator', country: 'Costa Rica', flag: '🇨🇷', status: 'Filled', statusCls: 'b-filled', days: 46, recruiter: 'A. Okafor', prio: 'High', prioCls: 'b-high' },
    { id: 'REQ-84284', title: 'Heavy Equipment Mechanic', country: 'Ghana', flag: '🇬🇭', status: 'On Hold', statusCls: 'b-hold', days: 59, recruiter: 'R. Tanaka', prio: 'Medium', prioCls: 'b-med' },
    { id: 'REQ-84321', title: 'Exploration Geologist', country: 'Australia', flag: '🇦🇺', status: 'Open', statusCls: 'b-open', days: 88, recruiter: 'C. Mendoza', prio: 'Low', prioCls: 'b-low' },
    { id: 'REQ-84358', title: 'HSE Coordinator', country: 'Peru', flag: '🇵🇪', status: 'Cancelled', statusCls: 'b-cancelled', days: 96, recruiter: 'S. Patel', prio: 'Critical', prioCls: 'b-crit' },
    { id: 'REQ-84395', title: 'Metallurgist', country: 'Suriname', flag: '🇸🇷', status: 'Filled', statusCls: 'b-filled', days: 148, recruiter: 'L. Nguyen', prio: 'High', prioCls: 'b-high' },
    { id: 'REQ-84432', title: 'Electrical Supervisor', country: 'Papua New Guinea', flag: '🇵🇬', status: 'On Hold', statusCls: 'b-hold', days: 105, recruiter: 'D. Brooks', prio: 'Medium', prioCls: 'b-med' },
    { id: 'REQ-84469', title: 'Mine Planning Engineer', country: 'Chile', flag: '🇨🇱', status: 'Filled', statusCls: 'b-filled', days: 190, recruiter: 'F. Asante', prio: 'Low', prioCls: 'b-low' },
    { id: 'REQ-84506', title: 'Supply Chain Analyst', country: 'Costa Rica', flag: '🇨🇷', status: 'Open', statusCls: 'b-open', days: 34, recruiter: 'M. Reyes', prio: 'Critical', prioCls: 'b-crit' },
    { id: 'REQ-84543', title: 'Drill & Blast Engineer', country: 'Ghana', flag: '🇬🇭', status: 'Filled', statusCls: 'b-filled', days: 55, recruiter: 'A. Okafor', prio: 'High', prioCls: 'b-high' },
    { id: 'REQ-84580', title: 'Environmental Specialist', country: 'United States', flag: '🇺🇸', status: 'Open', statusCls: 'b-open', days: 42, recruiter: 'R. Tanaka', prio: 'Medium', prioCls: 'b-med' },
    { id: 'REQ-84617', title: 'Maintenance Planner', country: 'Canada', flag: '🇨🇦', status: 'On Hold', statusCls: 'b-hold', days: 68, recruiter: 'C. Mendoza', prio: 'Low', prioCls: 'b-low' },
    { id: 'REQ-84654', title: 'Geotechnical Engineer', country: 'Mexico', flag: '🇲🇽', status: 'Cancelled', statusCls: 'b-cancelled', days: 71, recruiter: 'S. Patel', prio: 'Critical', prioCls: 'b-crit' },
    { id: 'REQ-84691', title: 'Fixed Plant Technician', country: 'Dominican Rep.', flag: '🇩🇴', status: 'Filled', statusCls: 'b-filled', days: 74, recruiter: 'L. Nguyen', prio: 'High', prioCls: 'b-high' },
    { id: 'REQ-84728', title: 'Procurement Lead', country: 'Australia', flag: '🇦🇺', status: 'Filled', statusCls: 'b-filled', days: 85, recruiter: 'D. Brooks', prio: 'Medium', prioCls: 'b-med' },
    { id: 'REQ-84765', title: 'Mobile Maintenance Lead', country: 'Peru', flag: '🇵🇪', status: 'Open', statusCls: 'b-open', days: 90, recruiter: 'F. Asante', prio: 'Low', prioCls: 'b-low' },
  ],
  holdReasons: [
    { reason: 'Budget freeze / approval pending', count: 78, color: 'var(--amber)' },
    { reason: 'Hiring manager unavailable', count: 49, color: 'var(--accent)' },
    { reason: 'Org restructure', count: 37, color: 'var(--purple)' },
    { reason: 'Role scope under review', count: 28, color: 'var(--green)' },
    { reason: 'Visa / mobilization blocked', count: 20, color: 'var(--red)' },
  ],
  holdAging: [
    { bucket: '0–30 days', count: 64, color: 'var(--green)' },
    { bucket: '31–60 days', count: 71, color: 'var(--accent)' },
    { bucket: '61–90 days', count: 48, color: 'var(--amber)' },
    { bucket: '90+ days', count: 29, color: 'var(--red)' },
  ],
  holdByCountry: [
    { country: 'Chile', flag: '🇨🇱', count: 58 },
    { country: 'Papua New Guinea', flag: '🇵🇬', count: 41 },
    { country: 'Suriname', flag: '🇸🇷', count: 33 },
    { country: 'Peru', flag: '🇵🇪', count: 27 },
    { country: 'Australia', flag: '🇦🇺', count: 22 },
    { country: 'Other (8)', flag: '🌐', count: 31 },
  ],
};
