// AUTO-GENERATED at 2026-06-12T01:39:03.036Z
// DO NOT EDIT THIS FILE DIRECTLY. It is generated by scripts/aggregate-csv.js
// based on CSV data in the ../data/ directory.

export const realData = {
  "totalRequisitions": 19292,
  "uniqueReqIds": 18935,
  "statusDistribution": {
    "filled": 14205,
    "cancelled": 4072,
    "open": 729,
    "onHold": 219,
    "pendingApproval": 67
  },
  "fillRate": 73.6,
  "cancelRate": 21.1,
  "timeToFill": {
    "average": 78,
    "median": 62.9,
    "min": 0,
    "max": 1343.4,
    "count": 14199
  },
  "byFunction": [
    {
      "name": "Mine Operations",
      "count": 4530
    },
    {
      "name": "Mine Maintenance",
      "count": 2132
    },
    {
      "name": "Engineering & Technical Services",
      "count": 1324
    },
    {
      "name": "HR & People",
      "count": 1061
    },
    {
      "name": "Process Operations",
      "count": 1052
    },
    {
      "name": "Supply Chain Commercial",
      "count": 916
    },
    {
      "name": "Process Maintenance",
      "count": 885
    },
    {
      "name": "Other",
      "count": 794
    },
    {
      "name": "Asset Management",
      "count": 711
    },
    {
      "name": "Finance and Accounting",
      "count": 574
    },
    {
      "name": "IT",
      "count": 542
    },
    {
      "name": "Projects",
      "count": 527
    },
    {
      "name": "Health & Safety",
      "count": 515
    },
    {
      "name": "Technical Services and Laboratories",
      "count": 487
    },
    {
      "name": "Geology",
      "count": 461
    },
    {
      "name": "Mine Engineering",
      "count": 420
    },
    {
      "name": "Environmental, Social & Governance (ESG)",
      "count": 379
    },
    {
      "name": "Exploration",
      "count": 316
    },
    {
      "name": "Facilities and Camp Services",
      "count": 305
    },
    {
      "name": "Metallurgy",
      "count": 248
    },
    {
      "name": "Sustainability",
      "count": 189
    },
    {
      "name": "Business Planning",
      "count": 152
    },
    {
      "name": "Security",
      "count": 139
    },
    {
      "name": "External Relations",
      "count": 132
    },
    {
      "name": "Legal & Compliance",
      "count": 100
    },
    {
      "name": "Communications",
      "count": 88
    },
    {
      "name": "Strategy",
      "count": 46
    },
    {
      "name": "Treasury",
      "count": 42
    },
    {
      "name": "Land",
      "count": 33
    },
    {
      "name": "Tax",
      "count": 33
    },
    {
      "name": "Mine Leadership",
      "count": 31
    },
    {
      "name": "Risk Management",
      "count": 29
    },
    {
      "name": "Laboratories",
      "count": 26
    },
    {
      "name": "Corporate Development",
      "count": 22
    },
    {
      "name": "Investor Relations",
      "count": 15
    },
    {
      "name": "Investments & Value Management",
      "count": 14
    },
    {
      "name": "Resource Modeling",
      "count": 13
    },
    {
      "name": "Legacy & Closure",
      "count": 9
    }
  ],
  "byCountry": [
    {
      "name": "AU (Australia)",
      "count": 4836
    },
    {
      "name": "CA (Canada)",
      "count": 3836
    },
    {
      "name": "GH (Ghana)",
      "count": 2889
    },
    {
      "name": "US (United States)",
      "count": 2395
    },
    {
      "name": "AR (Argentina)",
      "count": 1112
    },
    {
      "name": "SR (Suriname)",
      "count": 921
    },
    {
      "name": "PG (Papua New Guinea)",
      "count": 858
    },
    {
      "name": "MX (Mexico)",
      "count": 769
    },
    {
      "name": "Unspecified",
      "count": 746
    },
    {
      "name": "PE (Peru)",
      "count": 558
    },
    {
      "name": "CR (Costa Rica)",
      "count": 352
    },
    {
      "name": "CL (Chile)",
      "count": 13
    },
    {
      "name": "GF (French Guiana)",
      "count": 4
    },
    {
      "name": "GT (Guatemala)",
      "count": 3
    }
  ],
  "byEltMember": [
    {
      "name": "Natascha Viljoen",
      "count": 7173
    },
    {
      "name": "Rob Atkinson",
      "count": 6027
    },
    {
      "name": "Unspecified",
      "count": 1281
    },
    {
      "name": "Jennifer Cmil",
      "count": 932
    },
    {
      "name": "Dean Gehring",
      "count": 775
    },
    {
      "name": "Francois Hardy",
      "count": 605
    },
    {
      "name": "Peter Toth",
      "count": 597
    },
    {
      "name": "Peter Wexler",
      "count": 378
    },
    {
      "name": "Nancy Buese",
      "count": 310
    },
    {
      "name": "Karyn Ovelmen",
      "count": 229
    },
    {
      "name": "Aaron Puna",
      "count": 223
    },
    {
      "name": "Stephen Gottesfeld",
      "count": 189
    },
    {
      "name": "Suzy Retallack",
      "count": 157
    },
    {
      "name": "Mark Casper",
      "count": 119
    },
    {
      "name": "Tom Palmer",
      "count": 89
    },
    {
      "name": "Marcelo Godoy",
      "count": 67
    },
    {
      "name": "Nancy Lipson",
      "count": 65
    },
    {
      "name": "Brian Tabolt",
      "count": 50
    },
    {
      "name": "Mark Ebel",
      "count": 17
    },
    {
      "name": "Randy Engel",
      "count": 8
    },
    {
      "name": "Scott Lawson",
      "count": 1
    }
  ],
  "byBusinessUnit": [
    {
      "name": "Operations (BU_1007)",
      "count": 8583
    },
    {
      "name": "Unspecified",
      "count": 4520
    },
    {
      "name": "Projects (BU_1003)",
      "count": 1012
    },
    {
      "name": "Human Resources (BU_1005)",
      "count": 837
    },
    {
      "name": "Technical Services (BU_1013)",
      "count": 785
    },
    {
      "name": "Finance (BU_1002)",
      "count": 770
    },
    {
      "name": "Supply Chain (BU_1008)",
      "count": 613
    },
    {
      "name": "Sustainability & Development (BU_1012)",
      "count": 531
    },
    {
      "name": "HSSE (BU_1004)",
      "count": 471
    },
    {
      "name": "Information Technology (BU_1010)",
      "count": 385
    },
    {
      "name": "Exploration (BU_1001)",
      "count": 298
    },
    {
      "name": "Facilities and Site Services (BU_1014)",
      "count": 267
    },
    {
      "name": "Legal and Land (BU_1006)",
      "count": 131
    },
    {
      "name": "Strategic Development (BU_1011)",
      "count": 57
    },
    {
      "name": "CEO Office (BU_1000)",
      "count": 9
    },
    {
      "name": "Corporate Communications (BU_1009)",
      "count": 8
    },
    {
      "name": "Musselwhite Mine (BU_MWM)",
      "count": 8
    },
    {
      "name": "Business Unit - History (BU_Z999)",
      "count": 3
    },
    {
      "name": "Shared Services-Service Enablement Group (BU_2010)",
      "count": 3
    },
    {
      "name": "Saddle (BU_Saddle)",
      "count": 1
    }
  ],
  "postings": {
    "total": 316,
    "byStatus": [
      {
        "name": "Posted",
        "count": 235
      },
      {
        "name": "Updated",
        "count": 81
      }
    ]
  },
  "holds": {
    "totalRecords": 23709,
    "uniqueReqIds": 15429
  },
  "openReqsAging": {
    "under30": 290,
    "between30and60": 226,
    "between60and90": 95,
    "over90": 118
  }
} as const;
