// AUTO-GENERATED at 2026-06-12T20:56:21.232Z
// DO NOT EDIT THIS FILE DIRECTLY. It is generated by scripts/aggregate-csv.js
// based on CSV data in the ../data/ directory.

export const realData = {
  "totalRequisitions": 18935,
  "totalRowsBeforeDedup": 19292,
  "uniqueReqIds": 18935,
  "statusDistribution": {
    "filled": 13969,
    "cancelled": 3974,
    "open": 709,
    "onHold": 216,
    "pendingApproval": 67
  },
  "fillRate": 73.8,
  "cancelRate": 21,
  "timeToFill": {
    "average": 77.6,
    "median": 62.6,
    "min": 0,
    "max": 1343.4,
    "count": 13963
  },
  "byFunction": [
    {
      "name": "Mine Operations",
      "count": 4510
    },
    {
      "name": "Mine Maintenance",
      "count": 2128
    },
    {
      "name": "Engineering & Technical Services",
      "count": 1298
    },
    {
      "name": "Process Operations",
      "count": 1045
    },
    {
      "name": "HR & People",
      "count": 1031
    },
    {
      "name": "Supply Chain Commercial",
      "count": 886
    },
    {
      "name": "Process Maintenance",
      "count": 881
    },
    {
      "name": "Other",
      "count": 782
    },
    {
      "name": "Asset Management",
      "count": 696
    },
    {
      "name": "Finance and Accounting",
      "count": 564
    },
    {
      "name": "IT",
      "count": 517
    },
    {
      "name": "Projects",
      "count": 512
    },
    {
      "name": "Health & Safety",
      "count": 495
    },
    {
      "name": "Technical Services and Laboratories",
      "count": 473
    },
    {
      "name": "Geology",
      "count": 452
    },
    {
      "name": "Mine Engineering",
      "count": 412
    },
    {
      "name": "Environmental, Social & Governance (ESG)",
      "count": 357
    },
    {
      "name": "Facilities and Camp Services",
      "count": 305
    },
    {
      "name": "Exploration",
      "count": 283
    },
    {
      "name": "Metallurgy",
      "count": 248
    },
    {
      "name": "Sustainability",
      "count": 181
    },
    {
      "name": "Business Planning",
      "count": 149
    },
    {
      "name": "Security",
      "count": 135
    },
    {
      "name": "External Relations",
      "count": 124
    },
    {
      "name": "Legal & Compliance",
      "count": 95
    },
    {
      "name": "Communications",
      "count": 84
    },
    {
      "name": "Treasury",
      "count": 40
    },
    {
      "name": "Land",
      "count": 33
    },
    {
      "name": "Strategy",
      "count": 32
    },
    {
      "name": "Tax",
      "count": 32
    },
    {
      "name": "Mine Leadership",
      "count": 31
    },
    {
      "name": "Risk Management",
      "count": 28
    },
    {
      "name": "Laboratories",
      "count": 26
    },
    {
      "name": "Corporate Development",
      "count": 21
    },
    {
      "name": "Investor Relations",
      "count": 15
    },
    {
      "name": "Investments & Value Management",
      "count": 13
    },
    {
      "name": "Resource Modeling",
      "count": 12
    },
    {
      "name": "Legacy & Closure",
      "count": 9
    }
  ],
  "byCountry": [
    {
      "name": "AU (Australia)",
      "count": 4717
    },
    {
      "name": "CA (Canada)",
      "count": 3807
    },
    {
      "name": "GH (Ghana)",
      "count": 2869
    },
    {
      "name": "US (United States)",
      "count": 2233
    },
    {
      "name": "AR (Argentina)",
      "count": 1112
    },
    {
      "name": "SR (Suriname)",
      "count": 920
    },
    {
      "name": "PG (Papua New Guinea)",
      "count": 843
    },
    {
      "name": "MX (Mexico)",
      "count": 768
    },
    {
      "name": "Unspecified",
      "count": 740
    },
    {
      "name": "PE (Peru)",
      "count": 554
    },
    {
      "name": "CR (Costa Rica)",
      "count": 352
    },
    {
      "name": "CL (Chile)",
      "count": 13
    },
    {
      "name": "GF (French Guiana)",
      "count": 4
    },
    {
      "name": "GT (Guatemala)",
      "count": 3
    }
  ],
  "byEltMember": [
    {
      "name": "Natascha Viljoen",
      "count": 7087
    },
    {
      "name": "Rob Atkinson",
      "count": 6010
    },
    {
      "name": "Unspecified",
      "count": 1281
    },
    {
      "name": "Jennifer Cmil",
      "count": 902
    },
    {
      "name": "Dean Gehring",
      "count": 755
    },
    {
      "name": "Peter Toth",
      "count": 562
    },
    {
      "name": "Francois Hardy",
      "count": 497
    },
    {
      "name": "Peter Wexler",
      "count": 373
    },
    {
      "name": "Nancy Buese",
      "count": 310
    },
    {
      "name": "Aaron Puna",
      "count": 223
    },
    {
      "name": "Karyn Ovelmen",
      "count": 191
    },
    {
      "name": "Stephen Gottesfeld",
      "count": 185
    },
    {
      "name": "Suzy Retallack",
      "count": 143
    },
    {
      "name": "Mark Casper",
      "count": 119
    },
    {
      "name": "Tom Palmer",
      "count": 89
    },
    {
      "name": "Marcelo Godoy",
      "count": 67
    },
    {
      "name": "Nancy Lipson",
      "count": 65
    },
    {
      "name": "Brian Tabolt",
      "count": 50
    },
    {
      "name": "Mark Ebel",
      "count": 17
    },
    {
      "name": "Randy Engel",
      "count": 8
    },
    {
      "name": "Scott Lawson",
      "count": 1
    }
  ],
  "byBusinessUnit": [
    {
      "name": "Operations (BU_1007)",
      "count": 8564
    },
    {
      "name": "Unspecified",
      "count": 4505
    },
    {
      "name": "Projects (BU_1003)",
      "count": 996
    },
    {
      "name": "Human Resources (BU_1005)",
      "count": 799
    },
    {
      "name": "Finance (BU_1002)",
      "count": 751
    },
    {
      "name": "Technical Services (BU_1013)",
      "count": 698
    },
    {
      "name": "Supply Chain (BU_1008)",
      "count": 592
    },
    {
      "name": "Sustainability & Development (BU_1012)",
      "count": 499
    },
    {
      "name": "HSSE (BU_1004)",
      "count": 419
    },
    {
      "name": "Information Technology (BU_1010)",
      "count": 359
    },
    {
      "name": "Exploration (BU_1001)",
      "count": 295
    },
    {
      "name": "Facilities and Site Services (BU_1014)",
      "count": 267
    },
    {
      "name": "Legal and Land (BU_1006)",
      "count": 125
    },
    {
      "name": "Strategic Development (BU_1011)",
      "count": 34
    },
    {
      "name": "CEO Office (BU_1000)",
      "count": 9
    },
    {
      "name": "Corporate Communications (BU_1009)",
      "count": 8
    },
    {
      "name": "Musselwhite Mine (BU_MWM)",
      "count": 8
    },
    {
      "name": "Business Unit - History (BU_Z999)",
      "count": 3
    },
    {
      "name": "Shared Services-Service Enablement Group (BU_2010)",
      "count": 3
    },
    {
      "name": "Saddle (BU_Saddle)",
      "count": 1
    }
  ],
  "postings": {
    "total": 316,
    "byStatus": [
      {
        "name": "Posted",
        "count": 235
      },
      {
        "name": "Updated",
        "count": 81
      }
    ]
  },
  "holds": {
    "totalRecords": 23709,
    "uniqueReqIds": 15429
  },
  "openReqsAging": {
    "under30": 290,
    "between30and60": 223,
    "between60and90": 92,
    "over90": 104
  }
} as const;
