#!/usr/bin/env python3
"""Regenerate a simple knowledge index without altering raw sources."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE = ROOT / 'knowledge'
RAW = KNOWLEDGE / 'raw'
WIKI = KNOWLEDGE / 'wiki'
SCHEMA = KNOWLEDGE / 'schema'
INDEX = KNOWLEDGE / 'index.md'

def list_md(folder: Path):
    """List md.

    Args/Returns if relevant.
    """
    if not folder.exists():
        return []
    return sorted(p.relative_to(ROOT).as_posix() for p in folder.rglob('*.md'))

def section(title: str, items):
    """Section.

    Args/Returns if relevant.
    """
    lines = [f'## {title}', '']
    if items:
        lines.extend(f'- `{item}`' for item in items)
    else:
        lines.append('- None yet')
    lines.append('')
    return '\n'.join(lines)

def main() -> None:
    """Main.

    Args/Returns if relevant.
    """
    KNOWLEDGE.mkdir(exist_ok=True)
    RAW.mkdir(exist_ok=True)
    WIKI.mkdir(exist_ok=True)
    SCHEMA.mkdir(exist_ok=True)
    text = '# Knowledge Index\n\nGenerated by `scripts/generate_knowledge_index.py`. Edit descriptions manually after generation if useful.\n\n'
    text += section('Raw sources', list_md(RAW))
    text += section('Wiki pages', list_md(WIKI))
    text += section('Schema files', list_md(SCHEMA))
    text += '## Source fidelity rule\n\nEvery wiki page should say whether it is based on raw sources, official docs, user notes, synthesis, or assumptions.\n'
    INDEX.write_text(text, encoding='utf-8')
    print(f'Updated {INDEX.relative_to(ROOT)}')

if __name__ == '__main__':
    main()
