#!/usr/bin/env python3
"""wiki-reindex.py — Find wiki pages missing from index.md (orphans) and
rebuild index.md with category headers so every page is listed.

Idempotent: re-running with no orphans leaves the index unchanged in spirit
(same set of entries). Stdlib only, UTF-8 throughout.
"""
import sys
from datetime import datetime, timezone
from pathlib import Path

WIKI = Path(__file__).resolve().parent.parent / "knowledge" / "wiki"
# Category folder -> human header. Order here = order in the index.
CATEGORIES = [
    ("decisions", "Decisions"),
    ("patterns", "Patterns"),
    ("gotchas", "Gotchas"),
    ("metrics", "Metrics"),
    ("tools", "Tools"),
    ("projects", "Projects"),
    ("uncategorized", "Uncategorized"),
]


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def page_tags(path):
    """Pull the `tags:` line out of a page's frontmatter, if present."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            for ln in text[3:end].splitlines():
                if ln.strip().startswith("tags:"):
                    return ln.split(":", 1)[1].strip()
    return ""


def indexed_paths():
    """Rel paths already listed in index.md (same parse as wiki-lint.py)."""
    idx = WIKI / "index.md"
    if not idx.exists():
        return set()
    listed = set()
    for ln in idx.read_text(encoding="utf-8", errors="replace").splitlines():
        ln = ln.strip()
        if ln.startswith("- ") and " — " in ln:
            listed.add(ln[2:].split(" — ")[0].strip())
    return listed


def collect_by_category():
    """Return {category: [(rel, tags), ...]} for every page on disk."""
    by_cat = {}
    for folder, _ in CATEGORIES:
        path = WIKI / folder
        if not path.exists():
            continue
        for p in sorted(path.glob("*.md")):
            rel = p.relative_to(WIKI).as_posix()
            by_cat.setdefault(folder, []).append((rel, page_tags(p)))
    return by_cat


def main():
    before = indexed_paths()
    by_cat = collect_by_category()
    all_rels = {rel for items in by_cat.values() for rel, _ in items}
    orphans = sorted(all_rels - before)

    lines = ["# UNGASIS Wiki Index",
             "> Auto-generated by wiki-reindex.py. Do not edit manually.",
             f"Last updated: {now_iso()}", ""]
    for folder, header in CATEGORIES:
        items = by_cat.get(folder)
        if not items:
            continue
        lines.append(f"## {header}")
        for rel, tags in items:
            suffix = f" — tags: {tags}" if tags else " — tags:"
            lines.append(f"- {rel}{suffix}")
        lines.append("")

    (WIKI / "index.md").write_text("\n".join(lines).rstrip() + "\n",
                                   encoding="utf-8")
    with (WIKI / "log.md").open("a", encoding="utf-8") as f:
        f.write(f"[{now_iso()}] REINDEX: added {len(orphans)} orphan(s), "
                f"{len(all_rels)} total entries\n")

    print(f"Reindexed {len(orphans)} orphan pages. "
          f"Index now has {len(all_rels)} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
